### ISSUE TITLE
Fiskaltrust Service + Queue requiered on each till?

### ISSUE THREAD

**Issue by engelhuber** [fiskaltrust/interface-doc#100]
Hi all. I wanted to install the FT Service including Queue and TSE on our POS Server and all tills of the shop have to call the webservice of the server. So there wont be any FT component at the till computer.

But now I saw this structure which describes a queue on each till + the TSE at the server.
![image](https://user-images.githubusercontent.com/5049692/90497830-d6268e00-e147-11ea-9c02-05df67cc7609.png)

https://github.com/fiskaltrust/productdescription-de-doc/blob/11b278cf6f4d3c9db916aec52445ea1237ffbefb/for-posdealers/02-pre-sales/rollout-scenarios.md

Please let me know how to do. In the shops we have a POS/DB Server + n-tills

**Comment by aedler-ft** [comment]
yes, each till needs to have the local [fiskaltrust.Middleware](https://github.com/fiskaltrust/productdescription-de-doc/blob/master/product-service-description/compliance-as-a-service/produkte/4445-0003-lokal-installierte-middleware.md) installed, including a cashbox configured with a queue. with the rollout scenarios document which you linked above we described all prerequisites at the beginning of the document. in general, for n-tills you need n-queues. the queues will have to be notified to the tax office. the setup you described fits to the image you posted.

**Comment by engelhuber** [comment]
Thanks, I'll close this issue
