### ISSUE TITLE
Can I void / redo a cash up? Kann ich einen Tagesabschluss wiederholen / korrigieren?

### ISSUE THREAD

**Issue by Lorscheidt** [fiskaltrust/interface-doc#102]
Is it possible to void a cash up receipt when a cash up is redone in the system the same day?

**Comment by Lorscheidt** [comment]
How would I transmit the cash up number as asked for in DSFinV-k?

![image](https://user-images.githubusercontent.com/60941951/91177161-9af60300-e6e3-11ea-82b7-e30bb3a80594.png)

**Comment by mijomilicevic** [comment]
Hi, it is possible to create more than one "cash ups" on the same day. So i would not se the need to void it. Or why would you like to void it?
For the cash up i would recommend the ftReceiptIdentification which is returned by the ft Middleware.

**Comment by AxelKutschera** [comment]
I think: 
Sending a daily closing (cash up) to the middleware means only to have a marker for the later DSFinV-K export. The export always takes place between two daily-closing receipts.
If the daily closing receipt is sent several times a day, then there are several DSFinV-K exports. 
These are e.g. before a master data change also prescribed.
With each daily closing a Z_NR is incremented for DSFinV-K by the ft.Middleware.
With the "Audicon Kassenarchiv Online (AKO)", which is included in the carefree package, it will be possible to summarize several financial statements (also over several cash registers) via the fiskaltrust.Portal. 

Translated with www.DeepL.com/Translator (free version)

**Comment by Lorscheidt** [comment]
OK, great. Thanks for the answers.

So Z_NR is not filled by the ftReceiptIdentification?

**Comment by AxelKutschera** [comment]
As far as I know the Z_NR is managed by fiskaltrust. This also solves the problem that there are daily closings on different terminals.
Z_NR is not filled by the ftReceiptIdentification.

**Comment by Lorscheidt** [comment]
It does not yet answer the question though if cash ups can be voided e.g. when a mistake was done? The cash up would save the cash differences (Wechselgelddifferenzen) and the cash to bank amount (Geldtransfer). Sometimes this is done incorrectly and noticed straight after. It currently is allowed to redo a cash up to correct this. How does this work in the FT middleware? How do I log this correctly?

**Comment by Lorscheidt** [comment]
I think so as well. It won't be.
