### ISSUE TITLE
ftSignatureType - How does it work?

### ISSUE THREAD

**Issue by Lorscheidt** [fiskaltrust/interface-doc#104]
Hi everybody,

Could we please get more information on what to do with what is described here?
Samples?

 https://github.com/fiskaltrust/interface-doc/blob/master/doc/appendix-de-kassensichv/reference-tables/type-of-signature-ftsignaturetype.md/#L1

**Comment by Lorscheidt** [comment]
I found examples but am not yet 100% sure what we've to print on the receipt e.g. what does the Archiving required means? 
Could you maybe explain what information is mandatory to show for different use cases?

**Comment by aedler-ft** [comment]
you can find an overview of which content needs to be printed on a receipt here: https://github.com/fiskaltrust/faq/blob/master/images/20191122-ft-Belegmerkmale-DE-v0.5.pdf

**Comment by Lorscheidt** [comment]
Thanks, I know this. How does this translate to each ftSignatureType item?

What do I have to print for each receipt type?

**Comment by mijomilicevic** [comment]
Hi, all the values (ftSignatureTypes) returned in the Signatureblock of the response have to be printed on the receipt.

**Comment by Lorscheidt** [comment]
OK, this would be simple. Do you have German wording recommendations e.g. on the start receipt there is this:

"{
            ""ftSignatureFormat"": 13,
            ""ftSignatureType"": 4919338167972134929,
            ""Caption"": ""finish-transaction-payload"",
            ""Data"": ""aW5pdGlhbCBvcGVyYXRpb24gcmVjZWlwdCAvIHN0YXJ0LXJlY2VpcHQ=""
        }"

And I tend not to print finish-transaction-payload. :-)
