### ISSUE TITLE
When will the DieboldNixdorf TSE package be available in the live Portal?

### ISSUE THREAD

**Issue by engelhuber** [fiskaltrust/interface-doc#106]
The version list is currently empty
![image](https://user-images.githubusercontent.com/5049692/91055413-eac1c500-e624-11ea-8d17-07f01fa79a69.png)

I think it's because of the RC state?

**Comment by aedler-ft** [comment]
Exactly. If there exist only one package version, it is not listed in the list of package versions because you can download only this one version. DN SCU is still in RC phase; we'd be happy to receive some feedback so that we can validate a stable implementation!

**Comment by engelhuber** [comment]
OK, but when I try to save the SCU I get the following error: SCU konnte nicht erstellt werden.
After that a version list is available, but it seems to be the list of the CryptoVision TSE.

**Comment by engelhuber** [comment]
to give some feedback regarding the Diebold Nixdorf TSE: in the sandbox my test cases worked very well.
There are a lot of warnings, but it's working.
![image](https://user-images.githubusercontent.com/5049692/91159591-8bb58c00-e6c8-11ea-8cf0-a3997f300834.png)

**Comment by aedler-ft** [comment]
thank you a lot for the information; i've created an issue for that internally!

**Comment by engelhuber** [comment]
any news? 30.09. moves closer and closer...

**Comment by StefanKert** [comment]
@engelhuber,

we plan to release the Diebold to production this week. I´ll let you know as soon as it is available.

Beside the warnings, which are internal debug messages and will be changed to LogLevel Debug, did you face any issues with the Diebold Package? We are still trying to get detailed feedback on the implementation including long running tests (selftest, updatetime etc.) so if you did some extensive testing it would be cool if you could share additional details 👍

**Comment by engelhuber** [comment]
@StefanKert great, looking forward

So far I coudn't face any issues, except these warnings. The FT service is running stable for weeks now with the Diebold TSE. Sign works and the response time is ok.

**Comment by engelhuber** [comment]
let me know if I can perform any other tests

**Comment by StefanKert** [comment]
@engelhuber that sounds pretty good :) thanks for the insights.

> Sign works and the response time is ok.

What are the average response times that you are seeing? Any specific request that are very slow?

**Comment by engelhuber** [comment]
The avarage response time for pos-receipts and info-orders is about 1,2s
A zero-receipt takes about 3,2s

**Comment by StefanKert** [comment]
Hi @engelhuber,

thanks for the reply.

I am pretty sure we can improve these times in the near future, but I guess for now it is ok for an initial rollout.

The release package (1.3.6) is available now in the portal-de. Even though the version of the SCU is higher than the current released Queue version it is compatible.

![image](https://user-images.githubusercontent.com/7176615/92625866-7ac06980-f2c9-11ea-9b68-6fd619397167.png)

If you are facing any issues with the Diebold either get in touch through another issue or directly with support@fiskaltrust.de :) thanks a lot for contributing :)
