### ISSUE TITLE
cbUser field limits

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/interface-doc#108]
hi, the way i understand the  cbUser field describe in: https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/data-structures/data-structures.html?q=cbUser is that it is a mandatory String with 50 chars limit. Testing with the middleware i can send way more than 50 chars and also i can remove the field altogether ? How is that limit applied?

**Comment by christian-rogobete** [comment]
Hi @darek-phorest it is applied in the DSFinV-K export. Only 50 characters will be written there. pls. see BEDIENER_NAME in https://github.com/fiskaltrust/interface-doc/blob/master/doc/appendix-de-kassensichv/procedural-documentation/dsfinv-k-generation.md

**Comment by darek-phorest** [comment]
thanks Christian, the given example ` "ftReceiptCaseData":"{ ..., "UserId":192, ... }"` has the UserId prop as Int, we would like to send it as String so `"ftReceiptCaseData":"{ ..., "UserId": "userId", ... }"`, will that be ok on your side to process when creating the DSFinV-K export  ?

**Comment by TSchmiedlechner** [comment]
Hi @darek-phorest,
sorry for the late response! We're treating this field as a string internally too, you can therefore handle this exactly as you suggested. I'll fix this in the documentation as well :)

Just fyi, the string will be cut after the first 50 characters in the DSFinV-K if you send a longer string (as @christian-rogobete mentioned).
