### ISSUE TITLE
How to do manual Cash-In / -Out payments

### ISSUE THREAD

**Issue by engelhuber** [fiskaltrust/interface-doc#115]
I'm going to use the ReceiptCase **0x4445000000000011** (implicit) without ChargeItems. Instead of ChargeItems I'll use PayItemCase **0x4445000000000016** but I'm confused about the description:
_negative amount gets converted to GV_TYP=Einzahlung. 
positive amount gets converted to GV_TYP=Auszahlung. amount=-amount. in case of void-receipt everything turned_

In my opinion a positive amount have to be converted to a "Einzahlung" !?

**Comment by MarkusEGruber** [comment]
Hi engelhuber,

when you use that PayItemCase you also need to add the PayItemCase for cash (0x4445000000000001).

Einzahlung: negative amount on the cash transfer item (cash book), positive amount on the cash item
Auszahlung: positive amount on the cash transfer item (cash book), negative amount on the cash item

Does this answer your question?

**Comment by engelhuber** [comment]
ahhh, alright. Many thanks!
