### ISSUE TITLE
Correct documentation and take out 45 seconds reference

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/interface-doc#121]
Please update: This is not valid anymore - this 45 seconds stuff. :-)

https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/cash-register-integration/cash-register-integration.html#the-fiskaltrustsecuritymechanism-explicit-transaction

**Comment by TSchmiedlechner** [comment]
Hi, valid point! Thanks for the hint, we will update this soon (and let you know when it's done here).
Have a nice weekend!
