### ISSUE TITLE
Multi-purpose voucher redemption Problem within payItems

### ISSUE THREAD

**Issue by Melzer** [fiskaltrust/interface-doc#131]
Using 'ChargeItems' to redeem a voucher i will get following processData on the TSE: 
 - Beleg^7.00_0.00_0.00_0.00_-150.00^-143.00:Bar

Using 'PayItems' to redeem a voucher i will get this processData on the TSE:
 - Beleg^7.00_0.00_0.00_0.00_0.00^-143.00:Bar_150.00:Unbar

(values from examples section https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/examples/vouchers.html#multi-purpose-voucher-redemption)

Why is the PayItem not correctly transferd to 'GV_TYP = MehrzweckgutscheinEinlösung' like described under https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/reference-tables/type-of-payment-ftpayitemcase.html 'ftPayItemCase' = 0x444500000000000D

**Comment by TSchmiedlechner** [comment]
Hi @Melzer, sorry for the late response. This might indeed be an issue in the Middleware, we will have to look into this in detail and will get back to you as soon as possible.

**Comment by TSchmiedlechner** [comment]
Hello again! After checking this, the behavior seems okay to me. 
The reason is that in our interface-doc, _"DSFinV-K transformation required"_ means that we will convert this to the respective GV_TYP during the generation of our DSFinV-K export (and not before sending it to the TSE). At least in my quick test, this seems to be working properly for this case.

We should definitely point this out more clearly in our docs to avoid confusion, I created a workitem for this case.

I hope this helps,
Tom

**Comment by Melzer** [comment]
Hello @TSchmiedlechner,

The problem is, that when you do the transformation during the DSFinV-K generation, you will get a missmatch between processData and DSFinV-K. 

For example: 
ProcessData "Beleg^7.00_0.00_0.00_0.00_0.00^-143.00:Bar_150.00:Unbar" expect following DSFinV-K:
**businesscases.csv:** 
- GV_TYP=Umsatz with Z_UMS_BRUTTO=7

**payment.csv:** 
- ZAHLART_TYP=Bar with Z_ZAHLART_BETRAG=-143
- ZAHLART_TYP=Unbar with Z_ZAHLART_BETRAG=150

when you execute a transformation from payItem to chargeItem you will get following DSFinV-K:
**businesscases.csv:** 
- GV_TYP=Umsatz with Z_UMS_BRUTTO=7
- GV_TYP=MehrzweckgutscheinEinloesung with Z_UMS_BRUTTO=-150

**payment.csv:** 
- ZAHLART_TYP=Bar with Z_ZAHLART_BETRAG=-143

**_after the transformation you have a missmatch from DSFinV-K and ProcessData!_**

**Comment by TSchmiedlechner** [comment]
Hello,
sorry that it took us so long to get back to you here. Thanks a lot for the detailed explanations!
We have meanwhile fixed this issue in [version 1.3.19 of the Middleware](https://docs.fiskaltrust.cloud/docs/release-notes/middleware/1.3.19#bug-fix-wrong-tse-payload-when-transformed-payitems-are-used), PayItems are now transformed correctly.
