### ISSUE TITLE
DE: processType Bestellung-V1 bug in processData

### ISSUE THREAD

**Issue by Melzer** [fiskaltrust/interface-doc#137]
creating a request with ReceiptCase 0x4445000000000010 and payItems are empty i will get following processData:
- "1;\"Helles 0,5l\";3.50\n"
- or "1;\"Helles 0,5l\";3.50\n1;\"mit Glas\";.00\n"

refering to DSFinV-K v2.2 page 111f. it should be:
- "1;\"Helles 0,5l\";3.50\r"
- or "1;\"Helles 0,5l\";3.50\r1;\"mit Glas\";0\r"

**Comment by Melzer** [comment]
in my view of the DSFinV-K you should only use the row-delimiter "\r" if there are more than 1 elements. 
e.g.:
- "1;"Helles 0,5l";3.50"
- or "1;"Helles 0,5l";3.50\r1;"mit Glas";0.00"

**Comment by TSchmiedlechner** [comment]
Hi @Melzer, thank you very much for reporting this issue. This indeed looks like we're using the wrong row delimiter at a first glance, we'll have a closer look and get back to you when we have more details and/or a fix.

**Comment by TSchmiedlechner** [comment]
Hi @Melzer, we've investigated this issue and will include a fix in the upcoming version 1.3.14. Thanks again for reporting this!

**Comment by Melzer** [comment]
Hello @TSchmiedlechner, when do you expect version 1.3.14?

**Comment by TSchmiedlechner** [comment]
Most likely by the end of next week 👍

**Comment by Melzer** [comment]
Hi, i tried version 1.3.14 and the row-delimiter is now the correct symbol. But you still write ".00" as amount when quantity is 0.
In my view it should be "0.00".

**Comment by TSchmiedlechner** [comment]
Hi, thank you very much for validating this and for this information. You're correct, `0.00` would surely be cleaner here, we'll fix this in the next version.

**Comment by TSchmiedlechner** [comment]
This issue was fixed in [version 1.3.18](https://docs.fiskaltrust.cloud/docs/release-notes/middleware/1.3.18), thank you very much for your detailed tests!
