### ISSUE TITLE
QR-Code for AT

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/interface-doc#165]
Isn't the QR-Code (or according information if the printer is not capable to print graphics) mandatory for the Austrian market? If it is, this should be reflected in interface-doc/doc/appendix-at-rksv/data-structures/data-structures.md

**Comment by TSchmiedlechner** [comment]
Thanks for the idea (and sorry for the late response 😅). The fact that QR is mandatory is actually already described in the ftSignatureTypes page, and [here](https://docs.fiskaltrust.cloud/docs/poscreators/middleware-doc/austria/reference-tables#type-of-signature-ftsignatureformat) we've got some more detailed information about what should happen if the printer cannot print QR.

**Comment by AxelKutschera** [comment]
The QR-Code is not mandatory in AT. E.g. it is also possible to print a OCR-A-text.
You can find an overview here: https://www.fiskaltrust.at/wp-content/uploads/2017/07/170703_ft-Belegmerkmale.pdf
