### ISSUE TITLE
DE: Question about Portal-Setup. 1 Queue, 1 SCU, Mulitple cashboxes

### ISSUE THREAD

**Issue by AndreasEntscheffPinter** [fiskaltrust/interface-doc#170]
We're offering our customers a cloud-cashregister-system and to meet legal requirements we need to use the BringYourOwnDataCenter Solution for the fiskaltrust-DE interface.  
So the fiskaltrust-middleware will run in a container in our network and connect to a database that's also in our network.  
  
Each of our customers will get an own cashbox in the fiskaltrust portal.  
To make the setup process easy I'd like to use 1 queue and 1 signature creation unit for all cashboxes.  
At the end there will be 1 queue, 1 SCU (fiskaly) and multiple cashboxes.  
  
Is it possible to use the system that way? Or is it conflicting with legal requirements or technicals possibillites?

**Comment by TSchmiedlechner** [comment]
Hi @AndreasEntscheffPinter,
thanks for reaching out! Unfortunately, this scenario is not possible; as the Queue itself is an integral part of the "cash register" (according to the legal requirements), it has to be unique per customer (or, in German: "pro Kasse eine Queue"). 

I'd also recommend to use a separate SCU per CashBox, as this is usually simpler in the long run (easier to detect issues, etc.) Also, a SCU is strictly bound to _one_ TSE, hence I assume using one would anyway not work in your scenario (if I got it correctly).

However, we've several helpful resources to create large amounts of components, please refer to our [rollout documentation](https://docs.fiskaltrust.cloud/docs/posdealers/rollout-doc) for more details. I think that especially the [automation section](https://docs.fiskaltrust.cloud/docs/posdealers/rollout-doc/middleware#rollout-automation) might be interesting to you.

**Comment by AndreasEntscheffPinter** [comment]
Thank you @TSchmiedlechner for the detailled answer! :slightly_smiling_face:
