### ISSUE TITLE
DSFinV-K questions from customer

### ISSUE THREAD

**Issue by steininger** [fiskaltrust/interface-doc#173]
1) Feld BEDIENER_ID wird nicht befüllt im Export:
Wir übergeben den WaiterName als cbUser, da dies so Pflicht ist in Deutschland. 
Da es nur 1 Feld für Kellnerdaten gibt, kann keine Zusätzliche WaiterId übergeben werden.
Somit kann das BEDIENER_ID ja gar nicht befüllt werden.

2) Feld ZAHLART_NAME wird im Export nicht befüllt:
Von uns werden beide Daten, Description und ftPayItemCase, befüllt - somit sollte alles vorhanden sein. Trotzdem ist beim Export das Fehld ZAHLART_NAME leer.

3) Frage: Was bedeutet die laufende Nummer im Exportordner hinter dem Datum?
Vermutlich wird hier pro Tagesabschluss eine neue laufende Nummer erzeugt?

4) Warum heißt die im Exportverzeichnis abgelegte Datei gdpdu-01-09-2004.dto bzw. welchen Zusammenhang gibt es daduch zum DSFinV-K Export?

**Comment by mijomilicevic** [comment]
Hallo,

1. Die BEDIENER_ID kann mit `ftReceiptCaseData.UserId` übergeben werden.
2. Das Feld ZAHLART_NAME wird in `ftPayItemCaseData.ItemCaseName` übergeben.
3. Ja, diese Nummer wird mit jedem Tagesabschluss inkrementiert und ist die sogenannte Z_NR.
4. Das ist das XML Schema für die index.xml Datei (beide Dateien sind verpflichtend, und im DSFinV-K so definiert).

Hier die Doku zu Punkt 1 und 2: https://docs.fiskaltrust.cloud/docs/poscreators/middleware-doc/germany/dsfinv-k#procedural-documentation-for-dsfinv-k-generation

**Comment by AxelKutschera** [comment]
@4. "gdpdu-01-09-2004.DTO" sollte "gdpdu-01-09-2004.DTD" heißen.

**Comment by TSchmiedlechner** [comment]
Falls die Fragen nicht beantwortet sind, den Issue bitte wieder öffnen 🙂 

@AxelKutschera: absolut richtig, ist - denke ich - ein Tippfehler in der Frage. Unser Export gibt richtigerweise das `.dtd`-File aus.
