### ISSUE TITLE
ChargeItem mit Amount > 0 und Quantity = 0

### ISSUE THREAD

**Issue by Silvern29** [fiskaltrust/interface-doc#179]
Ein Kassenbeleg lässt sich mit Menge 0 und Gesamtbetrag größer 0 erstellen. Eine Bestellung mit den gleichen Daten erhält den Statuscode 400 zurück.

**Comment by TSchmiedlechner** [comment]
Hallo @Silvern29,
vielen Dank für den Hinweis, das Verhalten wirkt hier tatsächlich etwas inkonsistent. 

Die Ursache dafür ist, dass die TSE-Payload bei der Bestellung-V1 mit dem "Preis pro Stück" generiert werden muss, was sich natürlich bei einer `Quantity` von 0 nicht berechnen lässt. Der Kassenbeleg-V1 hat keinen direkten Bezug zur Menge, daher ist das Verhalten dort technisch zulässig.
