### ISSUE TITLE
Sending pos-receipt with same cbReceiptReference but additional Chargeitems 

### ISSUE THREAD

**Issue by Silvern29** [fiskaltrust/interface-doc#211]
Is it possible to send a pos-receipt again with the same cbReceiptReference but other Chargeitems, so they get added up to the original pos-receipt and receipt chain?

**Comment by TSchmiedlechner** [comment]
Hi @Silvern29,
1. Sending an additional POS receipt with the same `cbReceiptReference` does not alter the receipt chain, and both receipts will show up in the DSFinV-K. While they will be marked as linked, both will "generate turnover", therefore this behavior is not supported as you asked.
2. When cancelling or voiding receipts, please either set **either** the amount **or** the quantity negative, not both. I'm afraid that the docs are wrong here - apologies for the inconvenience, we'll fix this asap.
