### ISSUE TITLE
Fiskaltrust service doesn't run under Debian 10 and mono 5

### ISSUE THREAD

**Issue by mmatin2411** [fiskaltrust/interface-doc#214]
Log file:
10/22/2021 8:51:14 AM Trace-OnStart
10/22/2021 8:51:14 AM Trace-Load configuration from /opt/vendor/fiskaltrust/configuration.json
10/22/2021 8:51:17 AM Trace-Loading Helper Package fiskaltrust.service.helper.helipad, Version 1.2.19089.12258
10/22/2021 8:51:17 AM Trace-Error launching service, retry in 15s with download! (Object reference not set to an instance of an object.)
10/22/2021 8:51:17 AM Exception-Object reference not set to an instance of an object.
10/22/2021 8:51:32 AM Trace-Load configuration from /opt/vendor/fiskaltrust/configuration.json
10/22/2021 8:51:32 AM Trace-Downloading fiskaltrust.service.helper.helipad 1.2.19089.12258 updates ....

Configuration file:
{"helpers":[{"Id":"c32204ee-63d9-48c2-b548-acfb389fa713","Package":"fiskaltrust.service.helper.helipad","Version":"1.2.19089.12258","Configuration":{},"Url":[]}],"ftCashBoxId":"96b16e75-24b1-40ad-a6b5-780297aa0cd7","ftSignaturCreationDevices":[{"Id":"ff05e432-e675-4b0a-866a-4a77c3ec8a01","Package":"fiskaltrust.signing.atrustapdu","Version":"1.1.17313.3063","Configuration":{"serialnumber":"0x6ef24d21"},"Url":["http://localhost:1210/ff05e432-e675-4b0a-866a-4a77c3ec8a01"]}],"ftQueues":[{"Id":"d64678b4-daf7-49fa-8078-f78df6a759ae","Package":"fiskaltrust.service.sqlite.mono","Version":"1.2.21138.42021","Configuration":{"init_ftQueue":[{"ftQueueId":"d64678b4-daf7-49fa-8078-f78df6a759ae","ftCashBoxId":"96b16e75-24b1-40ad-a6b5-780297aa0cd7","ftCurrentRow":0,"ftQueuedRow":0,"ftReceiptNumerator":0,"ftReceiptTotalizer":0.0,"ftReceiptHash":null,"StartMoment":null,"StopMoment":null,"CountryCode":"AT","Timeout":15000,"TimeStamp":637704887716698186}],"init_ftQueueAT":[{"ftQueueATId":"d64678b4-daf7-49fa-8078-f78df6a759ae","CashBoxIdentification":"Kandolf-Fiskaltest2a","EncryptionKeyBase64":"cg1WVFspiPJudlB2l5sOQYkc/bHna19cK7Ujb6B88vY=","SignAll":false,"ClosedSystemKind":null,"ClosedSystemValue":null,"ClosedSystemNote":null,"LastSettlementMonth":0,"LastSettlementMoment":null,"LastSettlementQueueItemId":null,"SSCDFailCount":0,"SSCDFailMoment":null,"SSCDFailQueueItemId":null,"SSCDFailMessageSent":null,"UsedFailedCount":0,"UsedFailedMomentMin":null,"UsedFailedMomentMax":null,"UsedFailedQueueItemId":null,"UsedMobileCount":0,"UsedMobileMoment":null,"UsedMobileQueueItemId":null,"MessageCount":0,"MessageMoment":null,"LastSignatureHash":null,"LastSignatureZDA":null,"LastSignatureCertificateSerialNumber":null,"ftCashNumerator":0,"ftCashTotalizer":0.0,"TimeStamp":637704886940692949}],"init_ftSignaturCreationUnitAT":[{"ftSignaturCreationUnitATId":"ff05e432-e675-4b0a-866a-4a77c3ec8a01","Url":"http://localhost:1210/ff05e432-e675-4b0a-866a-4a77c3ec8a01","ZDA":"AT1","SN":"0x6ef24d21","CertificateBase64":"MIIFSjCCAzKgAwIBAgIEbvJNITANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBhMCQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0ExIzAhBgNVBAMMGkEtVHJ1c3QgUmVnaXN0cmllcmthc3NlLkNBMB4XDTE3MDMwNTEzNTIxMFoXDTIyMDMwNTEyNTIxMFowRjELMAkGA1UEBhMCQVQxIDAeBgNVBAMMF1N0ZXVlcm51bW1lciA0NjMxMy82MjU5MRUwEwYDVQQFEww0NDc2NDAxNzMxNTIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARpQhRdjp9Ldqv0EV846Smqz3OlFM94/FGfpwNmpDClyL2Cr4shGSjS7H4101o23WU89OgjwVabvR6vgVybmRalo4IBrTCCAakwfwYIKwYBBQUHAQEEczBxMEYGCCsGAQUFBzAChjpodHRwOi8vd3d3LmEtdHJ1c3QuYXQvY2VydHMvQS1UcnVzdC1SZWdpc3RyaWVya2Fzc2UtQ0EuY2VyMCcGCCsGAQUFBzABhhtodHRwOi8vb2NzcC5hLXRydXN0LmF0L29jc3AwDgYDVR0PAQH/BAQDAgbAMBEGA1UdDgQKBAhLsUeOH86IzTBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsLmEtdHJ1c3QuYXQvY3JsL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlLkNBMAkGA1UdEwQCMAAwWAYDVR0gBFEwTzBNBgYqKAARARgwQzBBBggrBgEFBQcCARY1aHR0cDovL3d3dy5hLXRydXN0LmF0L2RvY3MvY3AvQS1UcnVzdC1SZWdpc3RyaWVya2Fzc2UwEwYDVR0jBAwwCoAIQEeeruOQ37YwHAYDVR0RBBUwE4ERb2ZmaWNlQGthbmRvbGYuYXQwJAYHKigACgELAQQZDBdTdGV1ZXJudW1tZXIgNDYzMTMvNjI1OTANBgkqhkiG9w0BAQsFAAOCAgEATUFG5p3FomgvpP0ahuJcDw0WktTEDThS/yrOJt6UWejAhFvGJEBnq+aj2AKJMBBLg7oaaLH+INztGsafCq8ziPdYli6BzcFu5anH9Nk5toEXJAeV/gLB6O3M5/VFEdbgEahGa3PeeeqqotBX20/QXdNNbz35YNdog5n7PwAnOrQoFHyngA2xwkvDrzwaTeRRDg3Z69j2orwHoAqRWtzln+ESHBQGRv3eqycsFdpq2xKF5jJ0+DGHczeQIMwi0VytDpvXOpthZTbkqC98Bpvct14I+AGeHO8ufK49wNtkoJZ6Fz/rGDZaU8Vv6sDer2PiKlC0+6n31z+6w59uwVV/QZ19VvBPeqiSUp5SDc+g6yj8wRRjoSwdLjlYW3zSQ7q8/CC5OiGRGZx2ElSBq2xvyCX/30qSVfGRakFhpROJp1q8QGUgPmFehvFxN2MEnBAWQagvpbnsFydIJTpgmXrP1jWUKzLibnBF/gNPoYpT+75lWgBDbg3j5hl+2M63XxotCAoQ0p5NKQv7OuZalrzOylMpolHTC/jv3720f6BEI+KSG2V3dMCrTwFcPKEAoHJ8oCSWuCP6KFaLE92bHDkoRW3b7ALBw+qCWZ1FbFpEHNZRTs+CPhIOlhFoZCkPyuHZGk5KndphMz/pUE99ZW5Sk7qwaNhQ8+Y3H8rdumUce7g=","Mode":0,"TimeStamp":637704887716035237}],"init_ftSignaturCreationUnitDE":[],"init_ftSignaturCreationUnitFR":[],"init_ftCashBox":{"ftCashBoxId":"96b16e75-24b1-40ad-a6b5-780297aa0cd7","TimeStamp":637704887609817995}},"Url":["http://localhost:1200/fiskaltrust"]}],"TimeStamp":637704887765399554}

**Comment by fiscoal** [comment]
Did Mono 6 fix the issue?

**Comment by mmatin2411** [comment]
Same issue with mono 6.12.

**Comment by fiscoal** [comment]
Thanks for the feedback. Development seems to have been able to reproduce this in a quick and preliminary test, though it's not fully clear yet as to why. Will follow-up once we have more details, of course.

In the meantime, have lovely weekend.

**Comment by TSchmiedlechner** [comment]
Hi @mmatin2411,
thanks again for reporting this issue! Alex @fiscoal mentioned, we were able to reproduce and hopefully fix the issue. We've just released a new Mono Launcher, could you please try to re-build and re-download the Cashbox, and then try again?

Thanks again, and have a nice weekend!

**Comment by mmatin2411** [comment]
Hi @TSchmiedlechner,
We've tried with a new launcher, but still fiskaltrust doesn't fully start.
Here is a content of the service.log
11/8/2021 1:44:51 PM Trace-OnStart
11/8/2021 1:44:52 PM Trace-Load configuration from /opt/vendor/fiskaltrust/configuration.json
11/8/2021 1:44:53 PM Trace-Loading Helper Package fiskaltrust.service.helper.helipad, Version 1.2.19089.12258
11/8/2021 1:44:53 PM Trace-Error launching service, retry in 15s with download! (Object reference not set to an instance of an object.)
11/8/2021 1:44:53 PM Exception-Object reference not set to an instance of an object.
11/8/2021 1:45:08 PM Trace-Load configuration from /opt/vendor/fiskaltrust/configuration.json
11/8/2021 1:45:08 PM Trace-Downloading fiskaltrust.service.helper.helipad 1.2.19089.12258 updates ....
11/8/2021 1:45:18 PM Trace-Download done!
11/8/2021 1:45:22 PM Trace-Download done!
11/8/2021 1:45:22 PM Trace-Downloading fiskaltrust.service.sqlite.mono 1.2.21138.42021 updates ....
11/8/2021 1:45:29 PM Trace-Download done!
11/8/2021 1:45:29 PM Trace-Rename fiskaltrust.service.helper.helipad 1.2.19089.12258 updates ....
11/8/2021 1:45:29 PM Trace-Rename fiskaltrust.signing.atrustapdu 1.1.17313.3063 updates ....
11/8/2021 1:45:29 PM Trace-Rename fiskaltrust.service.sqlite.mono 1.2.21138.42021 updates ....
11/8/2021 1:45:29 PM Trace-Save configuration to /mnt/fiskaltrust/service/Configuration-aec1ed22-b527-4c8c-a61f-82704d330077.json
11/8/2021 1:45:29 PM Trace-Loading Helper Package fiskaltrust.service.helper.helipad, Version 1.2.19089.12258
11/8/2021 1:45:31 PM Trace-Error launching service, retry in 15s with download! (Object reference not set to an instance of an object.)
11/8/2021 1:45:31 PM Exception-Object reference not set to an instance of an object.

**Comment by TSchmiedlechner** [comment]
Hi, sorry to hear this. There might be an inconsistent state due to the previous issue. Was the Middleware used on this machine already? If not, could you please try to remove the service folder (after a backup, if there's a risk that there is production data in there), and try again?

**Comment by mmatin2411** [comment]
Hi, still same problem after service folder was deleted.

**Comment by fiscoal** [comment]
@mmatin2411, could you please drop me your contact details? I'd contact you for a follow-up call in that case.

Thanks.

**Comment by mmatin2411** [comment]
My contact details:
e-mail: mario.matin@kandolf.at
mob: +436604528887

**Comment by fiscoal** [comment]
Thanks, sent out invitation and redacted PII.

**Comment by fiscoal** [comment]
Clarified in private. There were two aspects to the issue

1. The temporary directory did not have sufficient disk space, which prevented the proper extraction of library binaries.
2. Mono 6.12 introduced changes to default paths. Using version 6.8 is advised for the time being.
