### ISSUE TITLE
Middleware ist regelmäßig nicht erreichbar

### ISSUE THREAD

**Issue by Silvern29** [fiskaltrust/interface-doc#234]
Die Middleware läuft beim Kunden in der VM-Ware der Swissbit-Stick ist als USB-Laufwerk verfügbar. Grundsätzlich funktioniert die Fiskalisierung.

Immer wieder ist die Middleware jedoch nicht ansprechbar. Inzwischen haben wir die neueste Version eingesetzt und loglevel auf Trace gesetzt. 

Im Log finden sich nun ca alle 10 Minuten Exceptions wie:

2022-01-05 10:20:05.216 +01:00 [DBG] WCF/REST Response | Method name: Journal | Request url: http://localhost:3076/59e6aa28-d221-4bad-8b5f-d0bd51ef4742/v0/journal?type=17477&from=637726381371991756&to=-1000
2022-01-05 10:20:05.240 +01:00 [ERR] Error while pushing entity data (17477, journalde)
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   bei System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   bei fiskaltrust.Middleware.Interface.Client.Http.HttpPos.fiskaltrust.ifPOS.v0.IPOS.Journal(Int64 ftJournalType, Int64 from, Int64 to)
   bei fiskaltrust.Middleware.Interface.Client.Common.RetryLogic.PosRetryProxyClient.<>c__DisplayClass10_0.<<Journal>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei fiskaltrust.Middleware.Interface.Client.Common.RetryLogic.RetryPolicyHandler`1.<>c__DisplayClass3_0`1.<<RetryFuncAsync>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei fiskaltrust.Middleware.Interface.Client.Common.RetryLogic.RetryPolicyHandler`1.<RetryFuncAsync>d__3`1.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bei fiskaltrust.Middleware.Helper.Helipad.AsyncEnumerablePOSWrapper.JournalAsync(JournalRequest request)
   bei fiskaltrust.Middleware.Helper.Helipad.Services.HelipadUploader.<UploadEntities>d__10.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei fiskaltrust.Middleware.Helper.Helipad.Services.HelipadUploader.<ProcessUploadWith>d__7.MoveNext()
---> (Interne Ausnahme #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   bei System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   bei fiskaltrust.Middleware.Interface.Client.Http.HttpPos.fiskaltrust.ifPOS.v0.IPOS.Journal(Int64 ftJournalType, Int64 from, Int64 to)
   bei fiskaltrust.Middleware.Interface.Client.Common.RetryLogic.PosRetryProxyClient.<>c__DisplayClass10_0.<<Journal>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei fiskaltrust.Middleware.Interface.Client.Common.RetryLogic.RetryPolicyHandler`1.<>c__DisplayClass3_0`1.<<RetryFuncAsync>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei fiskaltrust.Middleware.Interface.Client.Common.RetryLogic.RetryPolicyHandler`1.<RetryFuncAsync>d__3`1.MoveNext()<---

**Comment by fiscoal** [comment]
Was würde "nicht ansprechbar" in dem Kontext genau heissen? Sie bekommen auf einen Request keine Antwort von der Middleware? Oder einen Fehler?

Die Fehlermeldung würde darauf schliessen lassen, dass es Probleme bei der Kommunikation mit dem Portal gibt. Dies sollte grundsätzlich aber keinen Einfluss auf die Funktionalität an sich haben.

Hätten Sie hier eventuell einen Proxy im Einsatz? Hätten Sie bereits das Firewall Testskript von https://docs.fiskaltrust.cloud/de/docs/posdealers/rollout-doc/middleware#es-wird-keine-cloudbasierende-tse-verwendet ausprobiert, ob es alle Verbindungen als funktional ausgibt?

Am Idealsten wäre es, wenn Sie beim deutschen Customer Success Team (**support AT fiskaltrust.de**) ein Ticket aufmachen könnten und die vollständige Logdatei beifügen würden (am Besten reduziert auf die konkrete Fehlermeldung), sowie die CashBox ID.

Besten Dank und mit Verspätung bitte ein schönes neues Jahr.

**Comment by Silvern29** [comment]
Hallo! 

Vielen Dank für die rasche Antwort. Der Rest-Request erhält keine Antwort, also auch keine Fehlermeldung. Das Firewall-Testskript habe ich ohne Fehler ausgeführt.

Zeitlich scheint der Fehler immer mit einem der folgenden Requests aufzutauchen:
Request url: http://localhost:3076/59e6aa28-d221-4bad-8b5f-d0bd51ef4742/v0/journal?type=17477&from=637726381371991756&to=-1000
Diese lassen sich in unserer Testumgebung nicht finden?

Ich wünsche ebenfalls noch ein gutes neues Jahr

**Comment by fiscoal** [comment]
> Der Rest-Request erhält keine Antwort, also auch keine Fehlermeldung.

Wird die Verbindung geschlossen oder bleibt der Request einfach hängen und sie bekommen gar nichts oder ein Verbindungstimeout?

In dem Fall würde ich wie erwähnt ein Ticket beim deutschen Customer Success Team (support AT fiskaltrust.de) aufmachen und die vollständige Logdatei beifügen, sowie die CashBox ID und einen Screenshot von der Ausgabe vom Firewallskript (bitte darauf zu achten es mit der richtigen Konfigurationsdatei zu starten). Danke.

**Comment by fiscoal** [comment]
Danke für die Erstellung vom Ticket.

**Comment by fiscoal** [comment]
Just to summarise for future readers.

The error message was because of an upload glitch, which should be fixed in an upcoming version.
