### ISSUE TITLE
Extend hexadecimal values by decimal values

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#30]
To improve our interface documentation. Write the decimal value below for the hexadecimal value (ReceiptCase, ChargeItemCase, PayItemCase...). So that no conversion is necessary

**Comment by christian-rogobete** [comment]
Every programming language can work with hexadecimal numbers, so conversion should not be an issue. Furthermore the hexadecimal numbers can be better compared and flagged in this case.
