### ISSUE TITLE
Clarify failure scenarios 

### ISSUE THREAD

**Issue by TSchmiedlechner** [fiskaltrust/interface-doc#306]
We should clarify the different failure scenarios that are currently formulated in a slightly "overlapping" way [here](https://docs.fiskaltrust.cloud/docs/poscreators/middleware-doc/general/cash-register-integration/failure-scenarios).

In fact, there are IMO 3 scenarios to cover:
- **SCU not reachable**: Middleware goes into failed mode/circuit breaker mode, returns the ftState `0x02` -> Can be resolved via a zero receipt
- **Queue/MW not reachable**: No response from the Middleware, e.g. due to network or MW outage -> Receipts should be re-sent as soon as the MW is reachable again, using the flag `0x0000000000010000` to switch to late-signing mode. When the receipts are re-sent, failure-mode needs to be ended with a zero receipt
- **Cash register outage**: The whole cash register is not working anymore (e.g. because of a power outage), and the local regulations require to track handwritten receipts during that time -> Receipts should be re-sent to the Middleware after the systems are back online with the flag `0x0000000000080000`

**Comment by TSchmiedlechner** [comment]
@StefanKert @volllly @mijomilicevic would be curious about your thoughts about this as well :)

**Comment by volllly** [comment]
Yes I do agree with you about the three scenarios.

I think a problem that we have (which will be solved by the V2 Tagging) is that the case `Queue/MW not reachable` is in reality also two scenarios.

1. There is a bug/problem with the Middleware so its not signing (db access problem etc.)
2. There is a bug/problem in the implementation so the middleware is returning 4xx/5xx errors (e.g. the `ReceiptRequests` have an invalid structure)

**Comment by StefanKert** [comment]
> Yes I do agree with you about the three scenarios.
> 
> I think a problem that we have (which will be solved by the V2 Tagging) is that the case **Queue/MW not reachable** is in reality also two scenarios.
> 
> 1. There is a bug/problem with the Middleware so its not signing (db access problem etc.)
> 2. There is a bug/problem in the implementation so the middleware is returning 4xx/5xx errors (e.g. the `ReceiptRequests` have an invalid structure)

Also there is no difference for the caller IMO. The middleware is not reachable / can't process things. Something that we could mention though is if it is not reachable for a longer time or so.

In addition to that we could mention the fact that if they don't receive a response, or the cash register crashes, the first thing that they should do is perform a ReceiptRequest with the Request flag to see if something was processed already. By doing that we can at least sort out backchannel issues.
