### ISSUE TITLE
No sample JSONS available

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#31]
Add a few example JSONS or reference to the interface documentation

**Comment by TSchmiedlechner** [comment]
We're reworking our samples right now to support our (currently internal) business case database. Meanwhile, please find some JSON examples for Germany here:
https://github.com/fiskaltrust/middleware-de-demo-dotnet/tree/master/src/fiskaltrust.Middleware.Demo/ReceiptExamples

**Comment by christain-rogobete** [comment]
@TSchmiedlechner thank you for your answer. Can you please check the link? It is not working any more.

**Comment by TSchmiedlechner** [comment]
Thanks for the hint, @christian-rogobete. We recently added a Postman collection that contains those JSON examples:
https://github.com/fiskaltrust/middleware-demo-postman

**Comment by christian-rogobete** [comment]
Looks great, thank you @TSchmiedlechner
