### ISSUE TITLE
No introduction / instructions

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#34]
Quick Start Guide (own doc)
Quick practical introduction for the developer (10 points)
Set up cashbox
Set up a queue
Set up TSE
Set up helper
Download demo examples (JSON)

**Comment by christian-rogobete** [comment]
Hi @kaya77, 

thank you for reporting this issue. 

One can find further information regarding this topics specific for the German market on our German website : https://fiskaltrust.de

e.g. 
https://fiskaltrust.de/fiskaltrust/faq/faq-partner/
https://fiskaltrust.de/fiskaltrust/faq/videos/
https://fiskaltrust.de/fiskaltrust/faq/dokumente/

Demo examples are available here:

https://github.com/fiskaltrust/middleware-demo-postman
