### ISSUE TITLE
5.1.2.1 Zero Receipt (information about TSE) How is the information packed in the response.

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#37]

**Comment by christian-rogobete** [comment]
ftReceiptCaseFlag: 0x0000000000800000 has been added:

From the interface doc:
Request additional informations from used TSE device. This is valid for Zero-Receipts only and responses a TseInfo entry in ftStateData field. Content of this item is same as declared in the IDESSCD interface described at https://github.com/fiskaltrust/middleware-interface-dotnet/blob/master/src/fiskaltrust.ifPOS/v1/de/Models/TseInfo.cs
