### ISSUE TITLE
“35.3.3 Type of Service: ftChargeItemCase” => VAT concept

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#38]
Customers repeatedly ask how different VAT rates are represented; Introduction for 35.3.3 would be useful to explain the concept (in advance): All 7 VAT keys are repeated for different ChargeItem groups (sales, deposit, etc.)

**Comment by Lorscheidt** [comment]
I guess this should be clear enough from the documentation.

**Comment by christian-rogobete** [comment]
thanks @Lorscheidt
