### ISSUE TITLE
How to embed Sub JSON

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#39]
Some of the interface fields are used as containers for subordinated JSON code; for example: cbUser, cbCustomer, cbArea, ftChargeItemCaseData and others. A period with an example would be helpful to convey the concept clearly (incl. \ ”For quotes with embedded JSONs) Receipt responses should be included

You can define own field names and values therein, embedded in subordinated JSON, e.g.:

“cbCustomer”:  “{\”company\”: \”fiskaltrust\”, \”VAT-No\”: \”DE323821961\”, \”YourNumber\”: 123 }”

Backslashes are needed to insert subordinated quotes properly.
This writes the following script into cbCustomer (formatted):
						{  	
							“Company”: “fiskaltrust”,
							“VAT-No”: “DE323821961”,
							“YourNumber”: 123

**Comment by christian-rogobete** [comment]
Hello @kaya77, thank you for adding this issue. 

The following characters are reserved in JSON and must be properly escaped to be used in strings:

Backspace is replaced with \b
Form feed is replaced with \f
Newline is replaced with \n
Carriage return is replaced with \r
Tab is replaced with \t
Double quote is replaced with \"
Backslash is replaced with \\

This rule is not specific to our interface-doc but belongs to the specification of JSON. Pls. see also:
https://www.json.org/
