### ISSUE TITLE
Update System Requirements for the German service

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#40]
P.34 .NET version 4.0 still up to date? Which operating systems from which version are supported?

For example: System Requirements
.NET 4.6.1 Minimum requirement for the German service

**Comment by aedler-ft** [comment]
System Requirements are provided here:
https://github.com/fiskaltrust/productdescription-de-doc/blob/master/compliance-as-a-service/produkte/4445-0003-lokal-installierte-middleware.md
