### ISSUE TITLE
Search in the document problematic, error prone, because all markets in one document.

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#42]
Separation for each target market (country) a document (in EN and in the national language).
or place the respective abbreviations AT, FR, DE on each page

It would be good, as long as the AT, FR, DE document is in a pdf, to provide each page in the header or footer area with the respective abbreviation (AT, FR, DE) so that you can see at a glance whether you are in the document moved in the right country.

**Comment by TSchmiedlechner** [comment]
Fixed with the new, searchable web page (https://docs.fiskaltrust.cloud)
