### ISSUE TITLE
Non-existent values at ftReceiptCase

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#44]
Nevertheless (like others) it is listed in the ftReceiptCase list. Even an experienced colleague from Vienna accidentally used this wrong value because the docu confuses / misleads at first glance.
A receipt request (ftReceiptCase) 0x4445000000000003 does not exist at all!

Calls such as 0x4445000000000003 (initial operation receipt) etc. may ONLY be called implicitly, that is 0x4445000100000003. Why are users confused by mentioning these values without the implicit flag.

**Comment by christian-rogobete** [comment]
fixed, see https://github.com/fiskaltrust/interface-doc/blob/master/doc/appendix-de-kassensichv/reference-tables/reference-tables.md

**Comment by christian-rogobete** [comment]
fixed
