### ISSUE TITLE
It is not described for which ChargeItemcases whether and which values should be negated.

### ISSUE THREAD

**Issue by kaya77** [fiskaltrust/interface-doc#46]
It must be described for which ChargeItemcases whether and which values should be negated. (For counter bookings, discounts, etc.)

**Comment by christian-rogobete** [comment]
thank you for adding this issue, we will handle it in the receipt case definitions and we will add examples

**Comment by christian-rogobete** [comment]
see: https://github.com/fiskaltrust/interface-doc/tree/master/doc/appendix-de-kassensichv/receipt-case-definitions
