### ISSUE TITLE
No ftState for german market

### ISSUE THREAD

**Issue by TheFirstVoice** [fiskaltrust/interface-doc#49]

**Comment by christian-rogobete** [comment]
At this time there are no additional statuses for the german market. I will remove the table and add a new one as soon as special statuses for the german market will be available.

**Comment by christian-rogobete** [comment]
fixed 
https://github.com/fiskaltrust/interface-doc/blob/master/doc/appendix-de-kassensichv/reference-tables/service-status-ftstate.md
