### ISSUE TITLE
Necessary attribute names for DsFinV-K are are not defined.

### ISSUE THREAD

**Issue by TheFirstVoice** [fiskaltrust/interface-doc#50]
The middleware has to identify the necessary DsFinV-K field-names, but they are still not defined in interface doku and poscreator send strings or json-strings on their own. So it will be impossible for the programmes to extract the right DsFinV-K informations in produktion environment out of a string. JSON key-names have to be defined as early as possible.

**Comment by christain-rogobete** [comment]
please see https://github.com/fiskaltrust/interface-doc/issues/67
