### ISSUE TITLE
cbReceiptIdentification - instead of cbReceiptReference

### ISSUE THREAD

**Issue by LarsMach** [fiskaltrust/interface-doc#52]
A wrong field Name "cbReceiptIdentification" instead of "cbReceiptReference" occurs twice, and has been used by clients already - seemingly (aka reportedly) without returning errors…
...apart from ruining their software's requests to the middleware when it comes to linking transactions of a process.

**Comment by LarsMach** [comment]
cbReceiptIdentification does not exist.

**ft**ReceiptIdentification does (as part of a response)

**Comment by christian-rogobete** [comment]
Thank you! Fixed.
