### ISSUE TITLE
AVBelegstorno can not be used

### ISSUE THREAD

**Issue by christain-rogobete** [fiskaltrust/interface-doc#57]
AVBelegstorno is used in the list of ftReceiptCaseFlags in the german appendix, but AVBelegstorno is not allowed for cash registers that are connected to a TSE.

From DFKA Taxonomie Kassendaten doc and from DSFinV-K doc:
Achtung! Sobald eine TSE an einer Kasse eingesetzt wird, ist es technisch nicht mehr möglich, den Transaktionstyp „AVBelegstorno“ korrekt zu verwenden, da jeder Beleg schon vor dem Setzen des Storno- Kennzeichens bereits durch die TSE signiert wurde. Insofern ist ein nachträgliches „Nullen“ eines Beleges nicht mehr möglich.

In my opinion, the flag 0x0000000000040000 should be removed.

**Comment by AxelKutschera** [comment]
If the ft.middleware is used with an "old" cash register (without TSE), the flag may be used.
This would allow an "old" cash register to use various functions of the ft.Portal as well as additional products (e.g. AKO).

**Comment by christain-rogobete** [comment]
Hello @AxelKutschera thank you for the fast reply. Currently we are not supporting "old" cash registers without TSE. In my opinion the flag should be used to flag "BON_STORNO". See. Chapter 4.2.2 Nachträgliche Vorgangs-Stornierungen in DSFinV-K => should not be removed as suggested in my first description but should be used as an indicator for "BON_STORNO". Appreciate your thoughts.

**Comment by AxelKutschera** [comment]
Created pull request: Fix the usage of the reverse/voided receipt-flag #58
https://github.com/fiskaltrust/interface-doc/pull/58
