### ISSUE TITLE
Which JSON-keywords are predefined?

### ISSUE THREAD

**Issue by TheFirstVoice** [fiskaltrust/interface-doc#66]

**Comment by christain-rogobete** [comment]
Hello @TheFirstVoice,

thank you for adding this issue. Can you please specify more detailed what you mean by JSON-keywords?

**Comment by christian-rogobete** [comment]
if you mean those for the geman market to be used for data needed for the DSFinV-K export please see https://github.com/fiskaltrust/interface-doc/blob/master/doc/appendix-de-kassensichv/procedural-documentation/dsfinv-k-generation.md
