### ISSUE TITLE
Describe and implement the DsFinV-K export

### ISSUE THREAD

**Issue by TheFirstVoice** [fiskaltrust/interface-doc#67]

**Comment by christain-rogobete** [comment]
Hello @TheFirstVoice,

thank you for adding this issue. You can find our procedural documentation to the DSFinV-K export here: https://github.com/fiskaltrust/interface-doc/blob/master/doc/appendix-de-kassensichv/procedural-documentation/dsfinv-k-generation.md

The implementation of the export is not part of this (documentation) repository.  

Thank you and best regards
