### ISSUE TITLE
How will the VAT be calculated in special cases? 

### ISSUE THREAD

**Issue by AxelKutschera** [fiskaltrust/interface-doc#84]
doc/appendix-de-kassensichv/procedural-documentation/dsfinv-k-generation.md 

For the DSFinV-K-Export, the VAT has to be indicate in the following fields.
POS_UST
ZI_BASISPREIS_UST
BON_UST
Z_UST

In some special cases (e.g. car spare part in the car repair shop) of taxation, the VAT ist not a percentage of the net-price (NETTO) or the gross-price.
The the VATAmount has to be used in the json-request to transmit the correct information.

rule: 
when DSFinV-K Umsatzsteuer-ID = "7" & VATRate = "0", then POS_UST = VATAmount (mandatory)

**Comment by christian-rogobete** [comment]
pls. see pull request: https://github.com/fiskaltrust/interface-doc/pull/85

**Comment by christian-rogobete** [comment]
pls. see https://github.com/fiskaltrust/interface-doc/blob/master/doc/appendix-de-kassensichv/data-structures/data-structures.md#charge-items-entry - field VATAmount
