### ISSUE TITLE
Which ReceiptCase for initial operation receipt / start-receipt ?

### ISSUE THREAD

**Issue by engelhuber** [fiskaltrust/interface-doc#89]
Hi all, which ReceiptCase should be used for an initial operation receipt? 
The doc **fiskaltrust-Business-Cases-in-JSON_deutsch_2020-03-03.pdf** describes **0x4445000100000003**, but the [appendix](https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/reference-tables/type-of-receipt-ftreceiptcase.html) describes **0x4445000000000003**

The same for out of operation receipt:
Doc:  0x4445000100000004
Appendix: 0x4445000000000004

Thanks!

**Comment by StefanKert** [comment]
Hi @engelhuber,

thanks for your question. This is actually a little bit confusing in the documentation.

To keep it very short: 

- initial-operation-receipt = 0x4445000100000003
- out-of-operation-receipt = 0x4445000100000004

These two requests (similar to the closing requests) need to be sent with the `implict-flag` (`0x0000000100000000`) to make sure that those actions don´t have to be called twice. This is also stated in the reference table, but maybe we should highlight that section, in the reference tables:

![image](https://user-images.githubusercontent.com/7176615/86752776-e2df9e80-c03f-11ea-89d0-f9c7a7bb50be.png)

Please let me know if I was able to clarify your question :)

**Comment by engelhuber** [comment]
Thanks for your quick reply @StefanKert 
I just found out that it has something to do with the Explicit and Implicit flow. I'm not familiar with these flows, but I'm watching your YouTube Video from the Webinar right now

**Comment by StefanKert** [comment]
You are welcome :)

If you need further information on the Implict/Explict flow differences we do have a section on this topic in our documentation: https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/cash-register-integration/cash-register-integration.html#the-fiskaltrustsecuritymechanism-implicit-transaction

If you have further questions to this topic please reopen the issue :). If there are questions on another topic we´d highly appreciate it if you could open another issue :) Thanks a lot
