### ISSUE TITLE
ReceiptCase zero-receipt

### ISSUE THREAD

**Issue by engelhuber** [fiskaltrust/interface-doc#90]
Hi all,

the ReceiptCase of the zero-receipt should be (implicit) **0x4445000100000002** (4919338172267102210).
This works. I get a receipt but with less information as shown in the webinar of the 03.06.2020. e.g. I can't see the open transactions.

In the webinar they used **0x4445000100800002** (4919338172275490818) which I can't find in any doc from fiskaltrust!?
If I use this case, I will get the ftStateData as a response to see the open transactions.

**Comment by TSchmiedlechner** [comment]
Hi @engelhuber,
The receipt case used in the webinar (`0x4445000100800002`) contains the additional ftReceiptCaseFlag `0x0000000000800000`, which can be sent to query the data you need from the TSE. This is documented here: https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/reference-tables/type-of-receipt-ftreceiptcase.html#ftreceiptcaseflag

Basically, it's a combination of
- `0x4445000000000002` (zero receipt case)
- `0x0000000100000000` (implicit flag)
- `0x0000000000800000` (additional information flag)

I hope this helps 🙂

**Comment by engelhuber** [comment]
thanks, I got it ;)
