### ISSUE TITLE
"Partner-FAQ"

### ISSUE THREAD

**Issue by hkhann30449** [fiskaltrust/interface-doc#93]
Hello. 
In your FAQ is a small failure in the text of the button four in point 9 "Workflow zur Einrichtung einer neue CashBox". The text is "Signaturerstellungseinheit zuordnen" instead of "Gebrauchte deutsche Signaturerstellungseinheit“. It was a little bit confusing me.

With regards
Heiko Krueger

**Comment by AxelKutschera** [comment]
Thanks for the hint - I changed the text.
