### ISSUE TITLE
Because is tax-relevant, no negative amount ist feasible for "down payment".

### ISSUE THREAD

**Issue by AxelKutschera** [fiskaltrust/interface-doc#99]
https://github.com/fiskaltrust/interface-doc/blob/master/doc/appendix-de-kassensichv/reference-tables/type-of-payment-ftpayitemcase.md

0x444500000000000F | down paymentnot taxableDSFinV-K transformation required. UST_Schluessel=5. **_negative amount gets converted to GV_TYP=Anzahlungseinstellung._** positive amount gets converted to GV_TYP=Anzahlungsaufloesung. amount=-amount. in case of void-receipt everyting turned. not valid for taxable down payments, where it is clearly defined what the service is for.
-- | --

A negative amount is not feasible. - See DSFinV-K page 105 "04 Behandlung von Anzahlungen" and related example 4.

**Comment by TSchmiedlechner** [comment]
Hi @AxelKutschera,
thanks for bringing this up! We'll fix this issue in the upcoming version 1.3.21, it's tracked internally via the WI#43249.
